package main

import (
	"fmt"
	"os"
	"strings"
)

// factorInfo describes a single verification factor for the help system.
type factorInfo struct {
	Name        string
	Tier        int
	Summary     string // one-line for help listing
	Description string // full explanation for 'teep help <factor>'
}

// tierInfo describes one verification tier.
type tierInfo struct {
	Number      int
	Name        string // e.g. "Core Attestation"
	Label       string // e.g. "Tier 1: Core Attestation"
	Description string
}

// factorRegistry contains all verification factors in report order.
var factorRegistry = []factorInfo{
	// Tier 1: Core Attestation
	{
		Name:    "nonce_match",
		Tier:    1,
		Summary: "Response nonce matches request",
		Description: "Verifies that the nonce returned in the attestation response " +
			"matches the random nonce sent by the client. This prevents replay " +
			"attacks where an attacker presents a stale but valid attestation " +
			"from a previous session.",
	},
	{
		Name:    "tdx_quote_present",
		Tier:    1,
		Summary: "TDX quote is present in response",
		Description: "Checks that the intel_quote field exists in the attestation " +
			"response. The TDX quote is the cryptographic proof generated by " +
			"Intel TDX hardware that the code is running inside a genuine " +
			"Trusted Domain (TD). Without it, no hardware-level attestation " +
			"is possible.",
	},
	{
		Name:    "tdx_quote_structure",
		Tier:    1,
		Summary: "TDX quote parses as valid QuoteV4/V5",
		Description: "Parses the TDX quote binary and verifies it conforms to the " +
			"Intel QuoteV4 or QuoteV5 structure. On success, displays the " +
			"MRTD (Measurement of the initial TD image) prefix — a SHA-384 " +
			"hash of the VM image loaded by the VMM. Comparing MRTD against " +
			"a provider-published reference value is how you detect VM image " +
			"tampering. A malformed quote indicates data corruption or a " +
			"non-genuine attestation source.",
	},
	{
		Name:    "tdx_cert_chain",
		Tier:    1,
		Summary: "Intel root CA certificate chain valid",
		Description: "Verifies the X.509 certificate chain embedded in the TDX " +
			"quote traces back to the Intel SGX/TDX root CA. This proves the " +
			"quote was generated by genuine Intel hardware, not emulated or " +
			"spoofed.",
	},
	{
		Name:    "tdx_quote_signature",
		Tier:    1,
		Summary: "TDX quote signature verified",
		Description: "Verifies the ECDSA signature over the TDX quote body using " +
			"the attesting key from the certificate chain. This ensures the " +
			"quote has not been tampered with since generation.",
	},
	{
		Name:    "tdx_debug_disabled",
		Tier:    1,
		Summary: "Debug bit is 0 (production enclave)",
		Description: "Checks that the TD_ATTRIBUTES debug bit in the TDX quote is " +
			"not set. A debug enclave allows the host to inspect enclave " +
			"memory, which completely undermines confidentiality. Production " +
			"workloads must never run in debug mode.",
	},
	{
		Name:    "signing_key_present",
		Tier:    1,
		Summary: "Enclave public key present in response",
		Description: "Checks that the signing_key field exists in the attestation " +
			"response. Despite the field name, this is an ECDH public key " +
			"generated inside the TEE for key exchange, not for signing. " +
			"Without it, E2EE communication with the enclave is not possible.",
	},
	// Tier 2: Binding & Crypto
	{
		Name:    "tdx_reportdata_binding",
		Tier:    2,
		Summary: "REPORTDATA binds enclave key to quote",
		Description: "Verifies that the TDX REPORTDATA field contains a " +
			"keccak256-derived address of the enclave public key (last 20 " +
			"bytes of keccak256 of the uncompressed secp256k1 public key). " +
			"This cryptographically binds the ECDH key exchange key to the " +
			"attested enclave, preventing a man-in-the-middle from " +
			"substituting the key while leaving the TDX quote intact. " +
			"Without this binding, E2EE is security theater.",
	},
	{
		Name:    "intel_pcs_collateral",
		Tier:    2,
		Summary: "Intel PCS collateral fetched",
		Description: "Verifies that collateral (TCB info, CRLs) was successfully " +
			"fetched from the Intel Provisioning Certification Service (PCS). " +
			"Collateral is required for TCB currency and revocation checks. " +
			"Skipped in --offline mode or when the Intel PCS is unreachable.",
	},
	{
		Name:    "tdx_tcb_current",
		Tier:    2,
		Summary: "TEE TCB status from Intel PCS",
		Description: "Evaluates the TCB status returned by Intel PCS collateral " +
			"against the TDX quote. Passes for UpToDate and SWHardeningNeeded " +
			"(software mitigations applied). Fails for OutOfDate or Revoked " +
			"(firmware has known vulnerabilities). Also reports Intel Security " +
			"Advisory IDs (e.g. INTEL-SA-00837) when applicable. In --offline " +
			"mode, shows only the raw TEE_TCB_SVN bytes.",
	},
	{
		Name:    "nvidia_payload_present",
		Tier:    2,
		Summary: "NVIDIA attestation payload present",
		Description: "Checks that the nvidia_payload field exists in the attestation " +
			"response. This payload contains GPU attestation data (either an " +
			"EAT token or JWT) that proves the inference is running on a " +
			"genuine NVIDIA GPU with confidential computing enabled.",
	},
	{
		Name:    "nvidia_signature",
		Tier:    2,
		Summary: "NVIDIA payload signature verified",
		Description: "Verifies the cryptographic signature on the NVIDIA attestation " +
			"payload. For EAT tokens, this validates SPDM ECDSA P-384 " +
			"signatures on each GPU's cert chain. For JWTs, this verifies " +
			"the token against NVIDIA's JWKS (JSON Web Key Set) endpoint.",
	},
	{
		Name:    "nvidia_claims",
		Tier:    2,
		Summary: "NVIDIA attestation claims valid",
		Description: "Validates the claims within the NVIDIA attestation payload, " +
			"including GPU architecture, driver version, and confidential " +
			"computing mode. For EAT tokens, checks per-GPU evidence " +
			"claims. For JWTs, checks the overall attestation result.",
	},
	{
		Name:    "nvidia_nonce_match",
		Tier:    2,
		Summary: "NVIDIA payload nonce matches",
		Description: "Verifies that the nonce embedded in the NVIDIA attestation " +
			"payload matches the nonce submitted by the client. This proves " +
			"the GPU attestation is fresh and was generated for this specific " +
			"verification session.",
	},
	{
		Name:    "nvidia_nras_verified",
		Tier:    2,
		Summary: "NVIDIA NRAS RIM measurement verification",
		Description: "Posts the GPU attestation evidence (EAT) to NVIDIA's Remote " +
			"Attestation Service (NRAS) for server-side measurement comparison " +
			"against NVIDIA's Reference Integrity Manifest (RIM). The RIM " +
			"contains known-good firmware hashes for each GPU model. NRAS " +
			"returns a signed JWT with the overall attestation result, which " +
			"is verified using NVIDIA's JWKS. This complements local SPDM " +
			"verification: local catches compromised evidence without trusting " +
			"NVIDIA's cloud; NRAS catches firmware measurement mismatches " +
			"that local verification cannot detect without the RIM. Skipped " +
			"in --offline mode or when the payload is JWT (already NRAS-verified).",
	},
	{
		Name:    "e2ee_capable",
		Tier:    2,
		Summary: "Enclave key supports E2EE key exchange",
		Description: "Validates that the enclave public key is a well-formed " +
			"secp256k1 uncompressed point suitable for ECDH key exchange. " +
			"When this passes, the proxy can establish an encrypted channel " +
			"with the enclave using ECIES (Elliptic Curve Integrated " +
			"Encryption Scheme).",
	},
	// Tier 3: Supply Chain & Channel Integrity
	{
		Name:    "tls_key_binding",
		Tier:    3,
		Summary: "No TLS key in attestation",
		Description: "No TLS certificate public key is embedded in the attestation " +
			"document. Without this, a man-in-the-middle at the vendor's load " +
			"balancer can intercept traffic even if a genuine TEE is running. " +
			"The TLS termination point is outside the attested boundary. This " +
			"is the single most critical gap for end-to-end security.",
	},
	{
		Name:    "cpu_gpu_chain",
		Tier:    3,
		Summary: "No CPU-GPU attestation binding",
		Description: "The CPU (TDX) and GPU (NVIDIA) attestations are verified " +
			"independently. The nonce match (factors 1, 8, 14) proves both " +
			"were requested together, but does not prove they come from the " +
			"same physical machine. An attacker with access to two TEE " +
			"machines could combine the CPU attestation from one with the " +
			"GPU attestation from another. " +
			"To pass this factor, the provider must create a cryptographic " +
			"binding between the two. The recommended approach: hash the " +
			"NVIDIA EAT evidence (or a digest of the GPU SPDM measurement " +
			"blocks) and extend it into an RTMR register (e.g. RTMR2) " +
			"using the TDG.MR.RTMR.EXTEND instruction before generating " +
			"the TDX quote. The verifier can then recompute the hash from " +
			"the NVIDIA payload and confirm it matches the RTMR value in " +
			"the quote. This requires no cooperation from Intel or NVIDIA " +
			"— RTMR extension is a standard TDX operation available to any " +
			"code running inside the TD, and the NVIDIA EAT is already " +
			"generated by the GPU driver inside the confidential VM. The " +
			"vendor's attestation service just needs to sequence the " +
			"operations: collect GPU evidence, extend RTMR, then generate " +
			"the TDX quote.",
	},
	{
		Name:    "measured_model_weights",
		Tier:    3,
		Summary: "No model weight hashes",
		Description: "The attestation does not include hashes of the model weight " +
			"files. The TDX MRTD proves the VM image is genuine (OS, " +
			"firmware, inference server), but it does not cover the model " +
			"weights loaded at runtime. Without weight measurement, a " +
			"compromised provider could load a backdoored model while " +
			"presenting valid hardware attestation. This requires runtime " +
			"measurement of weights into an RTMR register.",
	},
	{
		Name:    "build_transparency_log",
		Tier:    3,
		Summary: "No build transparency log",
		Description: "No Sigstore bundle or equivalent build transparency log entry " +
			"was found in the attestation. Venice provides a docker-compose " +
			"hash via dstack, which proves the deployment manifest hasn't " +
			"changed, but this is not an independent transparency log. " +
			"Without a reproducible build pipeline committed to an " +
			"immutable log, you cannot verify that the running code " +
			"matches a specific audited source revision.",
	},
	{
		Name:    "cpu_id_registry",
		Tier:    3,
		Summary: "CPU ID verified against Proof of Cloud",
		Description: "The CPU PPID is extracted from the PCK certificate embedded in " +
			"the TDX quote and verified against the Proof of Cloud registry " +
			"— a vendor-neutral, append-only log of hardware identities " +
			"independently verified by alliance members. When online " +
			"(default), the quote is submitted to trust-servers operated by " +
			"Secret Labs, Nillion, and iEx.ec using threshold multisig. " +
			"Use --offline to skip the registry check and show only the " +
			"extracted PPID.",
	},
	{
		Name:    "compose_binding",
		Tier:    3,
		Summary: "app_compose hash matches MRConfigID",
		Description: "Verifies that the SHA-256 hash of the app_compose manifest " +
			"(from info.tcb_info in the attestation response) matches the " +
			"MR_CONFIG_ID field in the TDX quote. The MRConfigID encodes " +
			"0x01 + sha256(app_compose), cryptographically binding the " +
			"docker-compose deployment manifest to the hardware attestation. " +
			"This proves the TEE is running the declared container images.",
	},
	{
		Name:    "sigstore_verification",
		Tier:    3,
		Summary: "Container images in Sigstore transparency log",
		Description: "Extracts container image sha256 digests from the docker-compose " +
			"manifest inside app_compose and checks each against the Sigstore " +
			"transparency log (search.sigstore.dev). Sigstore entries prove " +
			"the images were built through a verifiable CI/CD pipeline with " +
			"signed provenance. Skipped when no image digests are found.",
	},
	{
		Name:    "event_log_integrity",
		Tier:    3,
		Summary: "Event log replays to match quote RTMRs",
		Description: "Replays the TDX event log by extending each entry's SHA-384 " +
			"digest into the corresponding RTMR (Runtime Measurement Register) " +
			"starting from 48 zero bytes: RTMR_new = SHA384(RTMR_old || digest). " +
			"The four replayed RTMR values are compared against the RTMR values " +
			"in the TDX quote. A match proves the event log is authentic and " +
			"complete — no entries were added, removed, or modified. Skipped " +
			"when no event log entries are present in the attestation response.",
	},
	// Tier 4: Gateway Attestation (nearcloud only)
	{
		Name:    "gateway_nonce_match",
		Tier:    4,
		Summary: "Gateway nonce matches request",
		Description: "Verifies that the nonce returned by the cloud-api.near.ai gateway " +
			"matches the random nonce sent by the client. The gateway runs in its " +
			"own TDX enclave and has a separate nonce from the model attestation.",
	},
	{
		Name:    "gateway_tdx_quote_present",
		Tier:    4,
		Summary: "Gateway TDX quote present and parsed",
		Description: "Checks that the gateway's intel_quote field exists in the " +
			"gateway_attestation section and was successfully parsed. The gateway " +
			"TDX quote proves cloud-api.near.ai itself runs in a genuine Intel " +
			"TDX enclave.",
	},
	{
		Name:    "gateway_tdx_quote_structure",
		Tier:    4,
		Summary: "Gateway TDX quote valid QuoteV4/V5",
		Description: "Parses the gateway's TDX quote and verifies it conforms to " +
			"the Intel QuoteV4 or QuoteV5 structure. Displays the gateway's MRTD " +
			"prefix for comparison against published reference values.",
	},
	{
		Name:    "gateway_tdx_cert_chain",
		Tier:    4,
		Summary: "Gateway Intel root CA chain valid",
		Description: "Verifies the X.509 certificate chain in the gateway's TDX quote " +
			"traces back to the Intel SGX/TDX root CA, proving the gateway " +
			"attestation comes from genuine Intel hardware.",
	},
	{
		Name:    "gateway_tdx_quote_signature",
		Tier:    4,
		Summary: "Gateway TDX quote signature verified",
		Description: "Verifies the ECDSA signature on the gateway's TDX quote body " +
			"using the attesting key from the certificate chain, ensuring the " +
			"gateway quote has not been tampered with.",
	},
	{
		Name:    "gateway_tdx_debug_disabled",
		Tier:    4,
		Summary: "Gateway debug bit is 0 (production)",
		Description: "Checks that the gateway's TD_ATTRIBUTES debug bit is not set. " +
			"A debug gateway enclave would allow the host to inspect all traffic " +
			"passing through the API gateway.",
	},
	{
		Name:    "gateway_tdx_reportdata_binding",
		Tier:    4,
		Summary: "Gateway REPORTDATA binds TLS fingerprint + nonce",
		Description: "Verifies the gateway TDX quote REPORTDATA field. " +
			"Checks REPORTDATA[32:64] matches the client nonce and " +
			"REPORTDATA[0:32] matches sha256(tls_cert_fingerprint). " +
			"Fails if the gateway uses an unknown REPORTDATA scheme.",
	},
	{
		Name:    "gateway_compose_binding",
		Tier:    4,
		Summary: "Gateway compose hash matches MRConfigID",
		Description: "Verifies that the SHA-256 hash of the gateway's app_compose " +
			"manifest matches the MR_CONFIG_ID field in the gateway's TDX quote, " +
			"binding the gateway's deployment manifest to its hardware attestation.",
	},
	{
		Name:    "gateway_cpu_id_registry",
		Tier:    4,
		Summary: "Gateway CPU registered in Proof of Cloud",
		Description: "Checks whether the gateway host machine is registered in the " +
			"Proof of Cloud registry using the gateway's TDX quote. Validates " +
			"hardware provenance for the gateway CVM when online checks are enabled.",
	},
	{
		Name:    "gateway_event_log_integrity",
		Tier:    4,
		Summary: "Gateway event log replayed, RTMRs match quote",
		Description: "Replays the gateway's TDX event log entries to recompute " +
			"the four RTMR values, then compares them against the RTMRs in the " +
			"gateway's TDX quote. Ensures the gateway's runtime measurement " +
			"history has not been tampered with.",
	},
}

// tierRegistry describes the verification tiers.
var tierRegistry = []tierInfo{
	{
		Number: 1,
		Name:   "Core Attestation",
		Label:  "Tier 1: Core Attestation",
		Description: "Factors 1-7. Validates that a TDX quote is present, " +
			"structurally valid, properly signed by Intel hardware, and not " +
			"from a debug enclave. Also checks the nonce for replay protection " +
			"and that an enclave public key exists for E2EE. A Tier 1 failure means " +
			"the attestation cannot be trusted at all.",
	},
	{
		Number: 2,
		Name:   "Binding & Crypto",
		Label:  "Tier 2: Binding & Crypto",
		Description: "Factors 8-16. Validates cross-component binding: the enclave " +
			"public key is bound to the TDX REPORTDATA (preventing key " +
			"substitution attacks), NVIDIA GPU attestation is present and " +
			"locally verified, NVIDIA NRAS RIM measurement comparison " +
			"passes, and the enclave key supports E2EE key exchange. A " +
			"Tier 2 failure means the attestation is structurally valid but " +
			"may not provide the security guarantees needed for encrypted " +
			"inference.",
	},
	{
		Number: 3,
		Name:   "Supply Chain & Channel Integrity",
		Label:  "Tier 3: Supply Chain & Channel Integrity",
		Description: "Factors 17-24. The gold standard for TEE verification. " +
			"Covers TLS key binding, CPU-GPU attestation chain, measured " +
			"model weights, build transparency logs, hardware identity " +
			"registry, compose manifest binding, Sigstore verification, " +
			"and event log integrity. " +
			"These represent the supply-chain verification frontier.",
	},
	{
		Number: 4,
		Name:   "Gateway Attestation",
		Label:  "Tier 4: Gateway Attestation",
		Description: "Factors 25-32. Only applies to the nearcloud provider " +
			"(cloud-api.near.ai). Verifies the API gateway itself runs in " +
			"an Intel TDX enclave with its own TDX quote, certificate chain, " +
			"and compose binding. This proves all traffic is routed through " +
			"a TEE-attested gateway, not just that the model backend is attested.",
	},
}

// findFactorByName returns the factorInfo for the given name.
func findFactorByName(name string) (factorInfo, bool) {
	for _, f := range factorRegistry {
		if f.Name == name {
			return f, true
		}
	}
	return factorInfo{}, false
}

// runHelp dispatches to the appropriate help printer.
func runHelp(args []string) {
	if len(args) == 0 {
		printOverview()
		return
	}
	switch args[0] {
	case "serve":
		printServeHelp()
	case "verify":
		printVerifyHelp()
	case "tiers":
		printTiersHelp()
	case "factors":
		printFactorsHelp()
	default:
		if f, ok := findFactorByName(args[0]); ok {
			printFactorHelp(f)
			return
		}
		fmt.Fprintf(os.Stderr, "teep help: unknown topic %q\n\n", args[0])
		printOverview()
	}
}

// printOverview prints the top-level help message.
func printOverview() {
	fmt.Print(`teep — TEE attestation verifier and E2EE proxy for AI providers

Usage:
  teep serve   PROVIDER [flags]                    Start the HTTP proxy server.
  teep verify  PROVIDER --model M [flags]          Fetch and print attestation report.
  teep help    [topic]                             Show detailed help for a topic.

Global flags:
  --log-level LEVEL   Set log verbosity: debug, info, warn, error (default: info).

Help topics:
  serve       Detailed documentation for the serve command.
  verify      Detailed documentation for the verify command.
  tiers       Explain the verification tier scoring system.
  factors     List all verification factors with full descriptions.
  <factor>    Show details for a single factor (e.g. teep help tls_key_binding).

Environment variables:
  TEEP_CONFIG        Path to TOML config file.
  TEEP_LISTEN_ADDR   Override listen address (default: 127.0.0.1:8337).
  VENICE_API_KEY     Venice AI API key.
  NEARAI_API_KEY     NEAR AI API key (used by neardirect and nearcloud providers).
`)
}

// printServeHelp prints detailed help for the serve command.
func printServeHelp() {
	fmt.Print(`teep serve — Start the HTTP proxy server

Usage:
  teep serve PROVIDER [--offline] [--log-level LEVEL]

Arguments:
  PROVIDER   Provider name (venice, neardirect, nearcloud, phalacloud).

The proxy intercepts OpenAI-compatible chat completion requests, performs TEE
attestation verification against the upstream provider, and optionally enables
end-to-end encryption (E2EE) when the attestation passes.

Clients send requests to http://127.0.0.1:8337/v1/chat/completions (or the
address set by TEEP_LISTEN_ADDR) using the same format as the OpenAI API.

The proxy:
  1. Parses the model name to determine the upstream provider.
  2. Fetches and verifies TEE attestation for the provider.
  3. Caches passing attestation reports (TTL configurable).
  4. If E2EE is supported and attestation passes, encrypts the request
     body and decrypts the response using ECIES with the enclave's
     attested enclave public key.
  5. Forwards the request to the provider's API endpoint.

Configuration is loaded from the TOML file at $TEEP_CONFIG. Each provider
section specifies the base URL, API key, model mappings, and whether E2EE
is enabled.

Example TOML:
  [providers.venice]
  base_url = "https://api.venice.ai"
  api_key_env = "VENICE_API_KEY"
  e2ee = true

Flags:
	--offline           Skip external verification (Intel PCS, Proof of Cloud,
											Certificate Transparency).
  --log-level LEVEL   Set log verbosity: debug, info, warn, error (default: info).
`)
}

// printVerifyHelp prints detailed help for the verify command.
func printVerifyHelp() {
	fmt.Print(`teep verify — Fetch and print a TEE attestation verification report

Usage:
  teep verify PROVIDER --model MODEL [flags]

Arguments:
  PROVIDER   Provider name (venice, neardirect, nearcloud, phalacloud).

Connects to the specified provider's attestation endpoint, fetches the TEE
attestation for the given model, and runs all verification factors. The
report is printed to stdout; log messages go to stderr.

Required flags:
  --model MODEL     Model name as known to the provider.

Optional flags:
  --save-dir DIR    Save raw attestation data to DIR (JSON, TDX quote,
                    NVIDIA payload). Useful for debugging and offline analysis.
	--offline         Skip external verification (Intel PCS collateral,
										Proof of Cloud registry, Certificate Transparency).
										PPID is still extracted locally.
  --log-level LEVEL Set log verbosity: debug, info, warn, error (default: info).

Exit codes:
  0   All enforced factors passed (or no factors are enforced).
  1   At least one enforced factor failed, or a fatal error occurred.

Examples:
  teep verify venice --model e2ee-deepseek-r1-0528
  teep verify neardirect --model qwen2.5-72b-instruct --save-dir ./attestation-data
  teep verify nearcloud --model Qwen/Qwen3.5-122B-A10B --log-level debug
  teep verify venice --model e2ee-qwen3-32b --log-level debug

See 'teep help tiers' for how factors are scored, or 'teep help factors'
for descriptions of all verification factors.
`)
}

// printTiersHelp prints documentation about the 3-tier scoring system.
func printTiersHelp() {
	fmt.Print("Verification Tiers\n")
	fmt.Print(strings.Repeat("=", 19) + "\n\n")

	fmt.Printf("teep evaluates TEE attestation using up to %d factors organized into %d tiers.\n", len(factorRegistry), len(tierRegistry))
	fmt.Print(`Each factor produces a result: PASS, FAIL, or SKIP. Factors marked
[ENFORCED] in the report will cause the proxy to refuse requests when
they fail.

`)

	for _, tier := range tierRegistry {
		fmt.Printf("%s\n", tier.Label)
		fmt.Print(strings.Repeat("-", len(tier.Label)) + "\n")
		fmt.Print(wrapText(tier.Description, 0, 76) + "\n\n")

		fmt.Print("  Factors:\n")
		for i, f := range factorRegistry {
			if f.Tier == tier.Number {
				fmt.Printf("    %2d. %-30s %s\n", i+1, f.Name, f.Summary)
			}
		}
		fmt.Println()
	}

	fmt.Print(`Default enforced factors: nonce_match, tdx_debug_disabled,
signing_key_present, tdx_reportdata_binding. These can be overridden in
the TOML config file.

Run 'teep help factors' for full descriptions, or 'teep help <factor>'
for a single factor.
`)
}

// printFactorsHelp prints all 20 factors with full descriptions.
func printFactorsHelp() {
	fmt.Print("Verification Factors\n")
	fmt.Print(strings.Repeat("=", 20) + "\n\n")

	currentTier := 0
	for i, f := range factorRegistry {
		if f.Tier != currentTier {
			currentTier = f.Tier
			tier := tierRegistry[currentTier-1]
			fmt.Printf("%s\n\n", tier.Label)
		}
		fmt.Printf("  %2d. %s\n", i+1, f.Name)
		fmt.Print(wrapText(f.Description, 6, 76) + "\n\n")
	}
}

// printFactorHelp prints detailed help for a single factor.
func printFactorHelp(f factorInfo) {
	tier := tierRegistry[f.Tier-1]
	fmt.Printf("%s (%s)\n", f.Name, tier.Label)
	fmt.Print(strings.Repeat("-", len(f.Name)+len(tier.Label)+3) + "\n\n")
	fmt.Print(wrapText(f.Description, 0, 76) + "\n")
}

// wrapText wraps text to the given width with the given indent. Each line
// is prefixed with indent spaces. Words are not broken.
func wrapText(text string, indent, width int) string {
	words := strings.Fields(text)
	if len(words) == 0 {
		return ""
	}

	prefix := strings.Repeat(" ", indent)
	maxLineLen := width - indent

	var b strings.Builder
	lineLen := 0

	for i, word := range words {
		wLen := len(word)
		if i == 0 {
			b.WriteString(prefix)
			b.WriteString(word)
			lineLen = wLen
			continue
		}
		if lineLen+1+wLen > maxLineLen {
			b.WriteByte('\n')
			b.WriteString(prefix)
			b.WriteString(word)
			lineLen = wLen
		} else {
			b.WriteByte(' ')
			b.WriteString(word)
			lineLen += 1 + wLen
		}
	}

	return b.String()
}
