package nearcloud

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"net"
	"net/http"
	"strings"
	"testing"
	"time"

	"github.com/13rac1/teep/internal/attestation"
	"github.com/13rac1/teep/internal/tlsct"
	"github.com/13rac1/teep/internal/tlsct/testtls"
)

func TestFetchAttestation_HappyPath(t *testing.T) {
	testGatewayTransportBinding(t, "matching_gateway", true)
}

func TestFetchAttestation_TransportBindingFailures(t *testing.T) {
	for _, mode := range []string{"only_backend_matches", "missing", "malformed", "wrong_length", "redirect"} {
		t.Run(mode, func(t *testing.T) { testGatewayTransportBinding(t, mode, false) })
	}
}

func testGatewayTransportBinding(t *testing.T, mode string, wantSuccess bool) {
	t.Helper()
	testtls.RunWithFallbackRoot(t, func(t *testing.T, authority *testtls.Authority) {
		t.Helper()
		nonce := attestation.NewNonce()
		var fingerprint string
		ts := authority.NewTLSServerForHost(t, http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			if r.URL.Path != attestationPath {
				t.Error("redirect target received request")
			}
			if r.ProtoMajor != 2 {
				t.Error("attestation did not negotiate HTTP/2")
			}
			q := r.URL.Query()
			if q.Get("model") != "test-model" || q.Get("include_tls_fingerprint") != "true" || q.Get("signing_algo") != "ed25519" {
				t.Error("missing attestation query parameters")
			}
			if !tlsct.SPKIFingerprintsEqual(q.Get("nonce"), nonce.Hex()) {
				t.Error("nonce was not generated by client")
			}
			if r.Header.Get("Authorization") != "Bearer test-key" {
				t.Error("missing provider authorization")
			}
			if mode == "redirect" {
				w.Header().Set("Location", "/target")
				w.WriteHeader(http.StatusFound)
				return
			}
			gatewayFP := fingerprint
			switch mode {
			case "only_backend_matches":
				gatewayFP = strings.Repeat("ab", 32)
			case "missing":
				gatewayFP = ""
			case "malformed":
				gatewayFP = strings.Repeat("z", 64)
			case "wrong_length":
				gatewayFP = "ab"
			}
			body := nearcloudAttestationJSON(gatewayFP, nonce.Hex())
			if mode == "matching_gateway" {
				index := strings.LastIndex(body, gatewayFP)
				body = body[:index] + strings.Repeat("ab", 32) + body[index+len(gatewayFP):]
			}
			if mode == "only_backend_matches" {
				// Replace the model field only: its match cannot authorize the gateway.
				index := strings.LastIndex(body, gatewayFP)
				body = body[:index] + fingerprint + body[index+len(gatewayFP):]
			}
			_, _ = w.Write([]byte(body))
		}), gatewayHost)
		fp := sha256.Sum256(ts.Certificate().RawSubjectPublicKeyInfo)
		fingerprint = hex.EncodeToString(fp[:])
		base := tlsct.NewPooledTransport()
		base.DialContext = func(ctx context.Context, network, _ string) (net.Conn, error) {
			return (&net.Dialer{Timeout: time.Second}).DialContext(ctx, network, ts.Listener.Addr().String())
		}
		client := tlsct.NewHTTPClientWithTransport(5*time.Second, base, false)
		defer client.CloseIdleConnections()
		// The synthetic public-host certificate has no public-log SCTs.
		// This unit test selects offline CT policy to test attestation binding.
		a := NewAttester("test-key", true)
		a.SetClient(client)
		raw, err := a.FetchAttestation(context.Background(), "test-model", nonce)
		if !wantSuccess {
			if err == nil || raw != nil {
				t.Fatal("invalid gateway binding returned usable attestation")
			}
			return
		}
		if err != nil {
			t.Fatal(err)
		}
		if raw.TransportTLSAuthority != gatewayHost || !tlsct.SPKIFingerprintsEqual(raw.TransportTLSFingerprint, fingerprint) {
			t.Fatal("incorrect gateway transport identity")
		}
		if raw.GatewayAppCompose != "test-compose" {
			t.Fatal("gateway evidence was lost")
		}
	})
}
